/* Reads the browser product files in shop/ and emits backend/shared/catalog-data.js.
 *
 * The shop/**-data.js files stay the single place products are edited. They
 * assign to `window`, which does not exist on Cloudflare Workers, so this
 * script flattens them into a plain module both runtimes can import. */

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const backendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rootDir = path.resolve(backendDir, "..");
const outFile = path.join(backendDir, "shared", "catalog-data.js");

const SOURCES = [
    { file: "shop/shirts/shirts-data.js", global: "SHOP_SHIRTS", category: "shirts" },
    { file: "shop/prints/prints-data.js", global: "SHOP_PRINTS", category: "prints" },
    { file: "shop/more/more-data.js", global: "SHOP_MORE", category: "more" }
];

function readGlobalArray(absPath, globalName) {
    const sandbox = { window: {} };
    vm.createContext(sandbox);
    vm.runInContext(fs.readFileSync(absPath, "utf8"), sandbox, {
        filename: absPath,
        timeout: 2000
    });
    const items = sandbox.window[globalName];
    if (!Array.isArray(items)) {
        throw new Error(`${absPath} did not define window.${globalName}`);
    }
    return items;
}

function toCents(price, id) {
    const amount = Number(price);
    if (!Number.isFinite(amount) || amount < 0) {
        throw new Error(`Product "${id}" has an invalid price: ${price}`);
    }
    return Math.round(amount * 100);
}

/* Product images are written relative to the data file, e.g. "../../assets/x.png".
 * Convert to a site-absolute path so it can be turned into a URL anywhere. */
function toSitePath(dataFileAbs, imagePath) {
    if (!imagePath || typeof imagePath !== "string") {
        return "";
    }
    if (/^https?:\/\//i.test(imagePath)) {
        return imagePath;
    }
    const resolved = path.resolve(path.dirname(dataFileAbs), imagePath);
    const relative = path.relative(rootDir, resolved).split(path.sep).join("/");
    return relative.startsWith("..") ? "" : "/" + relative;
}

const products = [];
const seen = new Set();

for (const source of SOURCES) {
    const absPath = path.join(rootDir, source.file);
    for (const raw of readGlobalArray(absPath, source.global)) {
        if (!raw || typeof raw.id !== "string" || !raw.id) {
            throw new Error(`${source.file} contains a product with no id`);
        }
        if (seen.has(raw.id)) {
            throw new Error(`Duplicate product id: ${raw.id}`);
        }
        seen.add(raw.id);

        products.push({
            id: raw.id,
            title: String(raw.title || raw.id),
            category: source.category,
            priceCents: toCents(raw.price, raw.id),
            sizes: Array.isArray(raw.sizes) ? raw.sizes.map(String) : [],
            imagePath: toSitePath(absPath, (raw.images || [])[0])
        });
    }
}

const banner = "/* Generated by backend/scripts/build-catalog.mjs. Edit shop/**-data.js instead. */\n\n";
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, banner + "export const PRODUCTS = " + JSON.stringify(products, null, 4) + ";\n", "utf8");

console.log(`Wrote ${products.length} products to backend/shared/catalog-data.js`);
