/* Generated by backend/scripts/build-catalog.mjs. Edit shop/**-data.js instead. */

export const PRODUCTS = [
    {
        "id": "shirt1",
        "title": "Shirt 1",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/images/Shirt.png"
    },
    {
        "id": "shirt2",
        "title": "Shirt 2",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": ""
    },
    {
        "id": "shirt3",
        "title": "Shirt 3",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": ""
    },
    {
        "id": "shirt4",
        "title": "Shirt 4",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": ""
    },
    {
        "id": "shirt5",
        "title": "Shirt 5",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": ""
    },
    {
        "id": "shirt6",
        "title": "Shirt 6",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": ""
    },
    {
        "id": "shirt7",
        "title": "Shirt 7",
        "category": "shirts",
        "priceCents": 2500,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": ""
    },
    {
        "id": "print1",
        "title": "Print 1",
        "category": "prints",
        "priceCents": 1500,
        "sizes": [],
        "imagePath": "/assets/GalleryAssets/visual-art/ArtPiece.png"
    },
    {
        "id": "print2",
        "title": "Print 2",
        "category": "prints",
        "priceCents": 1500,
        "sizes": [],
        "imagePath": ""
    },
    {
        "id": "print3",
        "title": "Print 3",
        "category": "prints",
        "priceCents": 1500,
        "sizes": [],
        "imagePath": ""
    },
    {
        "id": "more1",
        "title": "More 1",
        "category": "more",
        "priceCents": 1000,
        "sizes": [],
        "imagePath": "/assets/images/Package.png"
    },
    {
        "id": "more2",
        "title": "More 2",
        "category": "more",
        "priceCents": 1000,
        "sizes": [],
        "imagePath": ""
    },
    {
        "id": "more3",
        "title": "More 3",
        "category": "more",
        "priceCents": 1000,
        "sizes": [],
        "imagePath": ""
    }
];
